### ISSUE TITLE
Tags imported from other file are not supported

### ISSUE THREAD

**Issue by TomaszG** [bahmutov/find-test-names#78]
In my tests, I'm using cypres-grep, where I'm importing tags from another file:

```js
// support/tags.js

const Scopes = {
  Smoke: 'SMOKE',
  WIP: 'WIP',
}

const Features = {
  Feat1: 'FEAT1',
  Feat2: 'FEAT2',
}

module.exports = {
  Scopes,
  Features,
}
```

```js
// e2e/test.cy.js

import { Features, Scopes } from '../support/tags'

describe('Edit foo', { tags: [Features.Feat1] }, () => {
  it('bar', { tags: [Scopes.Smoke] }, () => {
    (...)
  })
})
```

Unfortunately, `print-tests` is not able to parse such a combination, it fails with the following error:

```
DEBUG=print-tests pnpm exec print-tests 'apps/client/cypress/**/*.js'     
undefined:1
tags: [Scopes.Smoke]
       ^

ReferenceError: Scopes is not defined
    at eval (eval at getTags (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/find-test-names@1.28.4_@babel+core@7.21.4/node_modules/find-test-names/src/index.js:53:16), <anonymous>:1:8)
    at getTags (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/find-test-names@1.28.4_@babel+core@7.21.4/node_modules/find-test-names/src/index.js:53:16)
    at getIt (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/find-test-names@1.28.4_@babel+core@7.21.4/node_modules/find-test-names/src/index.js:210:16)
    at CallExpression (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/find-test-names@1.28.4_@babel+core@7.21.4/node_modules/find-test-names/src/index.js:701:38)
    at c (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:45:20)
    at Proxy.skipThrough (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:186:39)
    at c (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:44:24)
    at base.ExpressionStatement.base.ParenthesizedExpression.base.ChainExpression (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:204:37)
    at c (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:44:24)
    at Proxy.skipThrough (/Users/tomasz/Projects/<redacted>/node_modules/.pnpm/acorn-walk@8.2.0/node_modules/acorn-walk/dist/walk.js:186:39)

Node.js v18.13.0
```

**Comment by vincezipparro** [comment]
Having the same issue, did you find a solution?
